#!/usr/bin/env bash
#FizzBuzz

x=1

while [ $x -le 100 ]
do
    if [ $((x%15)) -eq 0 ]
       then
       echo FizzBuzz
       ((++x))
    elif [ $((x%3)) -eq 0 ]
    then
	  echo Fizz
	  ((++x))
    elif [ $((x%5)) -eq 0 ]
    then
	     echo Buzz
	     ((++x))
	  else
	      echo $x
	      ((++x))
	  fi
done
