#!/usr/bin/env bash
#Displays Best school 10 times, but on the 4th line says bad luck on 8th says good luck

i=1

while (( i < 11 ))
do
    if
	(( i == 4 ))
	then
	    echo bad luck
	    ((i++))
	elif
	    (( i == 8 ))
	    then
		echo good luck
		((i++))
    else
	echo Best School
	((i++))
		fi
done
