#!/usr/bin/env bash
# Displays numbers 1-20 then on appropriate lines lists countries that the number is bad luck
i=0

while (( i < 20 ))
do
    echo $((++i))
    case "$i" in
	4 )
	   echo bad luck from china ;;
	9 )
	   echo bad luck from Japan ;;
	17 )
	   echo bad luck from Italy ;;
    esac
    
done
